CREATE TABLE DEPARTAMENTO(
	CODIGO_DEPTO NUMBER NOT NULL, 
	NOMBRE_DEPTO VARCHAR(100), 
	CONSTRAINT DEPTA_PK PRIMARY KEY (CODIGO_DEPTO)
) TABLESPACE ELECCIONESTBS ;
CREATE PUBLIC SYNONYM
-- DROP TABLE DEPARTAMENTO ;

SELECT  * FROM DEPARTAMENTO ;

CREATE TABLE MUNICIPIO(
	CODIGO_MUNI NUMBER NOT NULL, 
	DEPTO_MUNI NUMBER NOT NULL, 
	NOMBRE_MUNI VARCHAR(100), 
	CONSTRAINT MUNI_PK PRIMARY KEY (CODIGO_MUNI, DEPTO_MUNI),
	CONSTRAINT DEPTO_MUNI_FK
    FOREIGN KEY (DEPTO_MUNI)
    REFERENCES DEPARTAMENTO(CODIGO_DEPTO)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE MUNICIPIO;

SELECT  * FROM MUNICIPIO ;

CREATE TABLE PARTIDO(
	CODIGO_PART NUMBER NOT NULL, 
	NOMBRE_PART VARCHAR(100), 
	CONSTRAINT PART_PK PRIMARY KEY (CODIGO_PART)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE PARTIDO;

SELECT * FROM PARTIDO;

CREATE  TABLE ELECCION(
	CODIGO_ELE NUMBER NOT NULL, 
	NOMBRE_ELE VARCHAR(100), 
	CONSTRAINT ELE_PK PRIMARY KEY (CODIGO_ELE)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE ELECCION;

SELECT  * FROM ELECCION ;

CREATE TABLE ACTA(
	NUMERO_MESA NUMBER NOT NULL, 
	TIPO_ELECCION NUMBER NOT NULL, 
	DEPARTAMENTO NUMBER NOT NULL,
	MUNICIPIO NUMBER NOT NULL, 
	PAPELETAS_RECIBIDAS NUMBER, 
	TOTAL_VOTOS_VALIDOS NUMBER, 
	VOTOS_NULOS NUMBER, 
	VOTOS_BLANCO NUMBER, 
	VOTOS_VALIDOS_EMITIDOS  NUMBER,
	VOTOS_INVALIDOS NUMBER, 
	IMAGEN VARCHAR(500), 
	ESTADO_IMAGEN VARCHAR(3), -- VAL, ANU, ACT
	CUADRA_ACTA VARCHAR(1), -- S o N 
	CONTEO_IMPUGNA NUMBER, 
	CONTEO_INSCRITOS NUMBER, 
	STACTA VARCHAR(3), -- VAL, ANU, ACT
	STESCAN VARCHAR(3), 
	STSFISIC VARCHAR(3), 
	STSTRANS VARCHAR(3), 
	CONSTRAINT ACTA_PK PRIMARY KEY (NUMERO_MESA, TIPO_ELECCION),
	
	CONSTRAINT DEPTO_ACTA_FK
    FOREIGN KEY (DEPARTAMENTO, MUNICIPIO)
    REFERENCES MUNICIPIO(DEPTO_MUNI, CODIGO_MUNI), 
    
	CONSTRAINT ELE_ACTA_FK
    FOREIGN KEY (TIPO_ELECCION)
    REFERENCES ELECCION(CODIGO_ELE)
	
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE ACTA;

SELECT  * FROM ACTA;

CREATE TABLE VOTO(
	VOTO_PARTIDO NUMBER NOT NULL, 
	VOTO_MESA NUMBER NOT NULL, 
	VOTO_ELECCION NUMBER NOT NULL, 
	VOTO_CANTIDAD NUMBER, 
	CONSTRAINT VOTO_PK PRIMARY KEY (VOTO_PARTIDO, VOTO_MESA, VOTO_ELECCION),
	
	CONSTRAINT PARTIDO_VOTO_FK
    FOREIGN KEY (VOTO_PARTIDO)
    REFERENCES PARTIDO(CODIGO_PART), 
    
	CONSTRAINT ACTA_VOTO_FK
    FOREIGN KEY (VOTO_MESA, VOTO_ELECCION)
    REFERENCES ACTA(NUMERO_MESA, TIPO_ELECCION)
) TABLESPACE ELECCIONESTBS;

-- DROP TABLE VOTO:

SELECT * FROM VOTO;
SELECT * FROM ACTA;
SELECT * FROM ELECCION;


commit;
alter session set "_ORACLE_SCRIPT"=true;
--GUEST
CREATE USER guest1 IDENTIFIED BY guest1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER guest2 IDENTIFIED BY guest2 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER guest3 IDENTIFIED BY guest3 DEFAULT TABLESPACE ELECCIONESTBS;
--MESAS
CREATE USER mesas1 IDENTIFIED BY mesas1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas2 IDENTIFIED BY mesas2 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas3 IDENTIFIED BY mesas3 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER mesas4 IDENTIFIED BY mesas4 DEFAULT TABLESPACE ELECCIONESTBS;
--IT
CREATE USER it1 IDENTIFIED BY it1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER it2 IDENTIFIED BY it2 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER it3 IDENTIFIED BY it3 DEFAULT TABLESPACE ELECCIONESTBS;
--ADMIN
CREATE USER admin1 IDENTIFIED BY admin1 DEFAULT TABLESPACE ELECCIONESTBS;
CREATE USER admin2 IDENTIFIED BY admin2 DEFAULT TABLESPACE ELECCIONESTBS;

GRANT CREATE ANY VIEW TO guest1;
GRANT CREATE SESSION TO guest1,guest2,guest3;
GRANT SELECT ON DEPARTAMENTO TO guest1,guest2,guest3;
GRANT SELECT ON MUNICIPIO TO guest1,guest2,guest3;
GRANT SELECT ON PARTIDO TO guest1,guest2,guest3;
GRANT SELECT ON ELECCION TO guest1,guest2,guest3;
GRANT SELECT ON ACTA TO guest1,guest2,guest3;
GRANT SELECT ON VOTO TO guest1,guest2,guest3;

GRANT CREATE SESSION TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT ON DEPARTAMENTO TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT ON MUNICIPIO TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT ON PARTIDO TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT ON ELECCION TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT  ON ACTA TO mesas1,mesas2,mesas3, mesas4;
GRANT SELECT,INSERT  ON VOTO TO mesas1,mesas2,mesas3, mesas4;

GRANT CREATE SESSION TO it1,it2,it3;
GRANT CREATE USER TO it1,it2,it3;
GRANT CREATE TABLE TO it1,it2,it3;
GRANT SELECT ON DEPARTAMENTO TO it1,it2,it3;
GRANT SELECT ON MUNICIPIO TO it1,it2,it3;
GRANT SELECT ON PARTIDO TO it1,it2,it3;
GRANT SELECT ON ELECCION TO it1,it2,it3;
GRANT SELECT ON ACTA TO it1,it2,it3;
GRANT SELECT ON VOTO TO it1,it2,it3;


GRANT CREATE SESSION TO admin1, admin2;
GRANT CREATE USER TO admin1, admin2;
GRANT CREATE TABLE TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON DEPARTAMENTO TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON MUNICIPIO TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON PARTIDO TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON ELECCION TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON ACTA TO admin1, admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON VOTO TO admin1, admin2;
commit;




