--información de los votos por municipio correspondiente al tipo de elección de municipio.
-- DPTO MUNI PARTIDO #VOTOS
SELECT DISTINCT ELECCION.NOMBRE_ELE,DEPARTAMENTO.NOMBRE_DEPTO,MUNICIPIO.NOMBRE_MUNI,   PARTIDO.NOMBRE_PART,SUM(ACTA.VOTOS_VALIDOS_EMITIDOS)
FROM ELECCIONES.VOTO, ELECCIONES.ACTA, ELECCIONES.MUNICIPIO, ELECCIONES.DEPARTAMENTO, ELECCIONES.PARTIDO, ELECCIONES.ELECCION
WHERE VOTO.VOTO_PARTIDO= PARTIDO.CODIGO_PART
AND VOTO.VOTO_MESA = ACTA.NUMERO_MESA
AND VOTO.VOTO_ELECCION = ACTA.TIPO_ELECCION
AND acta.tipo_eleccion = eleccion.codigo_ele
AND ACTA.DEPARTAMENTO = MUNICIPIO.DEPTO_MUNI
AND ACTA.MUNICIPIO = MUNICIPIO.CODIGO_MUNI
AND MUNICIPIO.DEPTO_MUNI = departamento.codigo_depto
GROUP BY ELECCION.nombre_ele,municipio.nombre_muni, departamento.nombre_depto, PARTIDO.NOMBRE_PART, acta.votos_validos_emitidos
ORDER BY ELECCION.nombre_ele,departamento.nombre_depto,municipio.nombre_muni;


--Alcalde   ALTA VERAPAZ CHISEC Todos   151

SELECT SUM(ACTA.votos_validos_emitidos)
FROM ELECCIONES.ACTA,ELECCIONES.VOTO,ELECCIONES.PARTIDO
WHERE VOTO.VOTO_PARTIDO= PARTIDO.CODIGO_PART
AND VOTO.VOTO_MESA = ACTA.NUMERO_MESA
AND VOTO.VOTO_ELECCION = ACTA.TIPO_ELECCION
AND ACTA.tipo_eleccion=2
AND ACTA.departamento=3
AND ACTA.municipio=12
AND PARTIDO.CODIGO_PART=4;



CREATE VIEW VOTOSPRESIDENTE 
AS
SELECT ELECCION.NOMBRE_ELE,DEPARTAMENTO.NOMBRE_DEPTO,MUNICIPIO.NOMBRE_MUNI,PARTIDO.NOMBRE_PART,SUM(ACTA.VOTOS_VALIDOS_EMITIDOS) AS TOTAL 
FROM ELECCIONES.VOTO, ELECCIONES.ACTA, ELECCIONES.MUNICIPIO, ELECCIONES.DEPARTAMENTO, ELECCIONES.PARTIDO, ELECCIONES.ELECCION
WHERE VOTO.VOTO_PARTIDO= PARTIDO.CODIGO_PART
AND VOTO.VOTO_MESA = ACTA.NUMERO_MESA
AND VOTO.VOTO_ELECCION = ACTA.TIPO_ELECCION
AND acta.tipo_eleccion = eleccion.codigo_ele
AND ACTA.DEPARTAMENTO = MUNICIPIO.DEPTO_MUNI
AND ACTA.MUNICIPIO = MUNICIPIO.CODIGO_MUNI
AND MUNICIPIO.DEPTO_MUNI = departamento.codigo_depto
GROUP BY ELECCION.nombre_ele,municipio.nombre_muni, departamento.nombre_depto, PARTIDO.NOMBRE_PART, acta.votos_validos_emitidos
ORDER BY ELECCION.nombre_ele,departamento.nombre_depto,municipio.nombre_muni
;
 
 
SELECT * FROM VOTOSPRESIDENTE;



 